import {useEffect,useState} from 'react';
import {Routes,Route,NavLink,Link,useLocation} from 'react-router-dom';
import {Menu,X,ArrowRight,Phone,Mail,MapPin,ChevronUp} from 'lucide-react';
import {HomePage,AboutPage,ServicesPage,ProjectsPage,IndustriesPage,ContactPage,QuotePage,NotFound} from './pages';

const nav=[['/','Home'],['/about','About'],['/services','Services'],['/projects','Projects'],['/industries','Industries'],['/contact','Contact']];
function Logo(){return <Link className="logo" to="/" aria-label="High Tech home"><span className="logo-mark">HT</span><span><b>HIGH TECH</b><small>Welders Consult Nigeria Ltd.</small></span></Link>}
function Navbar(){const [open,setOpen]=useState(false);const loc=useLocation();useEffect(()=>setOpen(false),[loc]);return <header className="navbar"><div className="container nav-inner"><Logo/><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open} aria-controls="primary-navigation">{open?<X/>:<Menu/>}</button><nav id="primary-navigation" className={open?'nav-links open':'nav-links'}>{nav.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}<Link className="btn btn-primary nav-cta" to="/quote">Request a Quote</Link></nav></div></header>}
function Footer(){return <footer><div className="container footer-grid"><div><Logo/><p>A diversified Nigerian company with interests in building, welding, manufacturing, installation, provisions, trading, and services.</p></div><div><h4>Quick Links</h4>{nav.slice(0,5).map(([to,l])=><Link key={to} to={to}>{l}</Link>)}</div><div><h4>Core Services</h4><Link to="/services">Welding</Link><Link to="/services">Manufacturing</Link><Link to="/services">Solar Energy</Link><Link to="/services">Security</Link><Link to="/services">Property</Link></div><div><h4>Contact</h4><a href="tel:+2348030965094"><Phone/>0803 096 5094<br/>0701 666 6399</a><a href="mailto:hightechnologycomplex@gmail.com"><Mail/>hightechnologycomplex@gmail.com<br/>hightechweldersconsult@gmail.com</a><span><MapPin/>No. 5, Block C, Gidan Doki, opposite WTC Roundabout, Long Man Road, Katsina.</span></div></div><div className="container footer-bottom"><span>© High Tech & Technology Welders Consult Nigeria Limited.</span><span>RC No. 1632978</span></div></footer>}
function ScrollToTop(){const {pathname}=useLocation();const [show,setShow]=useState(false);useEffect(()=>{window.scrollTo(0,0)},[pathname]);useEffect(()=>{const fn=()=>setShow(scrollY>500);addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[]);return show&&<button className="to-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top"><ChevronUp/></button>}
export function SectionHeader({eyebrow,title,text,light=false}){return <div className={'section-head '+(light?'light':'')}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function PageHero({eyebrow,title,text}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
export function CTA(){return <section className="cta"><div className="container"><div><span className="eyebrow">LET'S WORK TOGETHER</span><h2>Have a project in mind?</h2><p>Tell us about your requirements and let us know how we can help.</p></div><div className="actions"><Link className="btn btn-gold" to="/quote">Request a Quote <ArrowRight/></Link><Link className="btn btn-outline-light" to="/contact">Contact Us</Link></div></div></section>}
export function ContactCards(){return <div className="contact-cards"><a href="tel:+2348030965094"><Phone/><div><b>Call Us</b><span>0803 096 5094<br/>0701 666 6399</span></div></a><a href="mailto:hightechnologycomplex@gmail.com"><Mail/><div><b>Email Us</b><span>hightechnologycomplex@gmail.com<br/>hightechweldersconsult@gmail.com</span></div></a><div><MapPin/><div><b>Office Address</b><span>No. 5, Block C, Gidan Doki,<br/>Opposite WTC Roundabout,<br/>Long Man Road, Katsina,<br/>Katsina State, Nigeria.</span></div></div><div><MapPin/><div><b>Company Registration</b><span>RC No. 1632978<br/>Katsina, Katsina State, Nigeria</span></div></div></div>}
export default function App(){return <><Navbar/><main><Routes><Route path="/" element={<HomePage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/projects" element={<ProjectsPage/>}/><Route path="/industries" element={<IndustriesPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="/quote" element={<QuotePage/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/><ScrollToTop/></>}
