import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,CheckCircle2,Award,Lightbulb,Layers3,Handshake,Target,BookOpen,TrendingUp,MapPinned,Eye,HeartHandshake,ShieldCheck} from 'lucide-react';
import {services,industries,projects} from './data';
import {SectionHeader,PageHero,CTA,ContactCards} from './App';

function ServiceCard({service}){const Icon=service.icon;return <article className="service-card"><span className="icon-box"><Icon/></span><span className="card-number">{String(service.id).padStart(2,'0')}</span><h3>{service.title}</h3><p>{service.description}</p><Link to="/contact">Discuss this service <ArrowRight/></Link></article>}
function IndustryCard({item}){const Icon=item.icon;return <article className="industry-card" style={{backgroundImage:`linear-gradient(180deg,transparent,#052f23),url('${item.image}')`}}><Icon/><h3>{item.title}</h3></article>}
function ProjectCard({item}){return <article className="project-card"><div className="project-image"><img src={item.image} alt={item.title}/><span>{item.category}</span></div><div><h3>{item.title}</h3><p>Project details coming soon. Company-approved case studies will be added here.</p></div></article>}

export function HomePage(){return <>
 <section className="hero"><div className="container hero-content"><span className="hero-kicker">HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED</span><h1>Engineering quality.<br/><em>Building possibilities.</em><br/>Delivering excellence.</h1><p>A diversified Nigerian company delivering professional welding, manufacturing, energy, property and industrial solutions.</p><div className="actions"><Link className="btn btn-primary" to="/services">Explore Our Services <ArrowRight/></Link><Link className="btn btn-outline-light" to="/quote">Request a Quote</Link></div><span className="rc">Registered in Nigeria · RC No. 1632978</span></div><div className="hero-side"><span>14+</span><p>Service areas.<br/>One trusted partner.</p></div></section>
 <section><div className="container split"><div className="image-stack"><img src="https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85" alt="Industrial welding professional"/><div className="experience"><b>Nigeria</b><span>Based. Multi-sector focused.</span></div></div><div><span className="eyebrow">WHO WE ARE</span><h2>A diversified company built around quality and reliability.</h2><p>We bring practical capability to engineering, manufacturing, energy, agriculture, trading, property and transportation. Our multi-sector structure helps clients work with one accountable team across varied requirements.</p><ul className="check-list"><li><CheckCircle2/>Reliable project delivery</li><li><CheckCircle2/>Professional, client-focused service</li><li><CheckCircle2/>Solutions across diverse industries</li></ul><Link className="text-link" to="/about">Discover our company <ArrowRight/></Link></div></div></section>
 <section className="section-alt"><div className="container"><SectionHeader eyebrow="WHAT WE DO" title="Solutions designed to move business forward." text="Professional services across engineering, infrastructure, energy and commerce."/><div className="service-grid">{services.slice(0,6).map(s=><ServiceCard key={s.id} service={s}/>)}</div><div className="center"><Link className="btn btn-secondary" to="/services">View all 14 services <ArrowRight/></Link></div></div></section>
 <section><div className="container"><SectionHeader eyebrow="INDUSTRIES WE SERVE" title="Diverse expertise. One standard of excellence."/><div className="industry-grid">{industries.slice(0,4).map(i=><IndustryCard key={i.title} item={i}/>)}</div></div></section>
 <section className="why"><div className="container"><SectionHeader light eyebrow="WHY CHOOSE HIGH TECH?" title="Dependable capability for every challenge."/><div className="feature-grid">{[[Award,'Quality Service','Professional standards from planning to delivery.'],[Lightbulb,'Experienced Solutions','Practical answers shaped around client requirements.'],[Layers3,'Diverse Expertise','Multi-sector capability under one trusted company.'],[Handshake,'Client Commitment','Reliable communication and lasting relationships.']].map(([I,t,p])=><div key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
 <section><div className="container"><SectionHeader eyebrow="OUR OBJECTIVES" title="Creating value beyond every project."/><div className="objective-grid">{[[Target,'Deliver Quality'],[BookOpen,'Build Knowledge'],[TrendingUp,'Develop Businesses'],[MapPinned,'Support Local Development']].map(([I,t],n)=><div key={t}><span>0{n+1}</span><I/><h3>{t}</h3><p>{['Providing high-quality services and products.','Creating awareness through workshops and training.','Investing in sustainable business ventures.','Contributing to growth in Katsina State and Nigeria.'][n]}</p></div>)}</div></div></section>
 <section className="section-alt"><div className="container"><SectionHeader eyebrow="SELECTED WORK" title="Our project capabilities." text="Representative categories shown with development imagery; verified company project details will be added when supplied."/><div className="project-grid">{projects.slice(0,3).map(p=><ProjectCard key={p.title} item={p}/>)}</div></div></section>
 <section className="stats"><div className="container">{[['14+','Service Areas'],['Multi-Sector','Operations'],['100%','Commitment to Quality'],['Nigeria','Based']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section><CTA/><section className="home-contact"><div className="container"><SectionHeader eyebrow="CONTACT HIGH TECH" title="Ready to discuss your requirements?" text="Reach our team by phone or email, or visit us in Katsina State, Nigeria."/><ContactCards/></div></section>
 </>}

export function AboutPage(){return <><PageHero eyebrow="ABOUT HIGH TECH" title="A modern Nigerian company with diverse capability." text="Professional solutions driven by quality, reliability and a commitment to long-term value."/><section><div className="container split"><div><span className="eyebrow">COMPANY OVERVIEW</span><h2>Built to serve clients across essential industries.</h2><p>High Tech & Technology Welders Consult Nigeria Limited is a diversified company operating across welding, manufacturing, construction, trading, agriculture, solar energy, security, property and transportation.</p><p>Registered as RC No. 1632978, we are positioned to coordinate practical services and commercial solutions for organizations and communities in Katsina State and across Nigeria.</p></div><img className="rounded-image" src="https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=85" alt="Engineering team at work"/></div></section><section className="section-alt"><div className="container mission-grid"><div><Target/><span className="eyebrow">PROPOSED MISSION</span><h2>Reliable solutions. Sustainable value.</h2><p>To provide reliable, innovative and high-quality solutions across engineering, manufacturing, energy, trading and related industries while creating sustainable value for our clients and communities.</p><small>Content requires company approval before production launch.</small></div><div><Eye/><span className="eyebrow">PROPOSED VISION</span><h2>Recognized for excellence.</h2><p>To become a respected diversified Nigerian company recognized for quality, innovation, integrity and excellence across every sector in which we operate.</p><small>Content requires company approval before production launch.</small></div></div></section><section><div className="container"><SectionHeader eyebrow="OUR VALUES" title="The standards behind our work."/><div className="values">{['Integrity','Quality','Innovation','Reliability','Professionalism','Customer Satisfaction'].map((v,i)=><div key={v}><span>0{i+1}</span><h3>{v}</h3></div>)}</div></div></section><CTA/></>}

export function ServicesPage(){const [filter,setFilter]=useState('All');const groups={Engineering:[1,2],Energy:[6,7],Commercial:[3,4,8,9,11,12],Agriculture:[5],Security:[10],'Property & Mobility':[13,14]};const shown=filter==='All'?services:services.filter(s=>groups[filter].includes(s.id));return <><PageHero eyebrow="OUR SERVICES" title="Comprehensive solutions across multiple industries." text="One dependable company for engineering, supply, energy, commercial and development needs."/><section><div className="container"><div className="filters" aria-label="Filter services">{['All',...Object.keys(groups)].map(group=><button type="button" className={filter===group?'active':''} aria-pressed={filter===group} onClick={()=>setFilter(group)} key={group}>{group}</button>)}</div><div className="service-grid">{shown.map(s=><ServiceCard key={s.id} service={s}/>)}</div></div></section><CTA/></>}
export function IndustriesPage(){return <><PageHero eyebrow="INDUSTRIES" title="Sector knowledge that powers practical solutions." text="We organize our diverse capabilities around the industries our clients operate in."/><section><div className="container industry-grid full">{industries.map(i=><IndustryCard key={i.title} item={i}/>)}</div></section><CTA/></>}

export function ProjectsPage(){const [filter,setFilter]=useState('All');const cats=['All',...new Set(projects.map(p=>p.category))];return <><PageHero eyebrow="PROJECTS & PORTFOLIO" title="Capability in action." text="Explore the categories in which our team is positioned to deliver. Verified project case studies are coming soon."/><section><div className="container"><div className="filters">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==='All'||p.category===filter).map(p=><ProjectCard key={p.title} item={p}/>)}</div></div></section><CTA/></>}

const options=services.map(s=><option value={s.title} key={s.id}>{s.title}</option>);
function Form({quote=false}){const [sent,setSent]=useState(false);const submit=e=>{e.preventDefault();if(e.currentTarget.checkValidity()){setSent(true);e.currentTarget.reset()}};return <form onSubmit={submit} className="form"><div className="form-grid"><label>Full Name<input required name="name" placeholder="Your full name"/></label>{quote&&<label>Company / Organization<input name="company" placeholder="Company name"/></label>}<label>Email Address<input required type="email" name="email" placeholder="you@example.com"/></label><label>Phone Number<input required type="tel" name="phone" placeholder="0800 000 0000"/></label><label>Service {quote?'Required':'Interested In'}<select required defaultValue=""><option value="" disabled>Select a service</option>{options}</select></label>{quote&&<><label>Project Location<input required name="location" placeholder="City, State"/></label><label>Estimated Budget<select name="budget" defaultValue=""><option value="">Select a range</option><option>Under ₦500,000</option><option>₦500,000 – ₦2,000,000</option><option>₦2,000,000 – ₦10,000,000</option><option>Above ₦10,000,000</option></select></label><label>Preferred Start Date<input type="date" name="date"/></label></>}{!quote&&<label className="wide">Subject<input required name="subject" placeholder="How can we help?"/></label>}<label className="wide">{quote?'Project Description':'Message'}<textarea required rows="6" name="message" placeholder="Tell us about your requirements..."/></label></div><button className="btn btn-primary" type="submit">{quote?'Submit Quote Request':'Send Message'} <ArrowRight/></button>{sent&&<p className="success"><CheckCircle2/>Thank you. Your {quote?'quote request':'message'} has been received.</p>}</form>}
export function ContactPage(){return <><PageHero eyebrow="CONTACT US" title="Let’s start a conversation." text="Tell us about your requirement and our team will be ready to help."/><section><div className="container"><ContactCards/><div className="contact-layout"><div><span className="eyebrow">SEND A MESSAGE</span><h2>How can we help?</h2><p>Complete the form and our team will respond using the details you provide.</p><div className="contact-note"><HeartHandshake/><div><b>Prefer to speak directly?</b><p>Call 0803 096 5094 or 0701 666 6399.</p></div></div></div><Form/></div></div></section></>}
export function QuotePage(){return <><PageHero eyebrow="REQUEST A QUOTE" title="Tell us about your next project." text="Share a few details and help us understand the solution you need."/><section><div className="container narrow"><div className="quote-intro"><ShieldCheck/><div><h2>Project enquiry</h2><p>Your information will only be used to respond to this request.</p></div></div><Form quote/></div></section></>}
export function NotFound(){return <section className="not-found"><span>404</span><h1>Page not found</h1><p>The page you requested does not exist.</p><Link className="btn btn-primary" to="/">Return Home</Link></section>}
