import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,CheckCircle2,Award,HeartHandshake,Layers3,ShieldCheck,Target,BookOpen,TrendingUp,MapPinned} from 'lucide-react';
import {services,industries} from './data';
import {SectionHeader,PageHero,CTA,ContactCards} from './App';

function ServiceGallery({images}){const [activeIndex,setActiveIndex]=useState(0);useEffect(()=>{if(images.length<2||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=window.setInterval(()=>setActiveIndex(index=>(index+1)%images.length),4000);return()=>window.clearInterval(timer)},[images]);const activeImage=images[activeIndex];return <div className="service-gallery"><img key={activeImage.src} src={activeImage.src} alt={activeImage.alt} loading="lazy"/><div className="gallery-dots" aria-label={`Slide ${activeIndex+1} of ${images.length}`}>{images.map((image,index)=><span key={image.src} className={index===activeIndex?'active':''}/>)}</div></div>}
function ServiceCard({service}){const Icon=service.icon;const hasImages=service.images?.length;return <article className={`service-card${hasImages?' has-gallery':''}`}>{hasImages?<ServiceGallery images={service.images}/>:<span className="icon-box"><Icon/></span>}<span className="card-number">{String(service.id).padStart(2,'0')}</span><h3>{service.title}</h3><p>{service.description}</p><Link to="/contact">Discuss this service <ArrowRight/></Link></article>}
function IndustryCard({item}){const Icon=item.icon;return <article className="industry-card" style={{backgroundImage:`linear-gradient(180deg,transparent,#052f23),url('${item.image}')`}}><Icon/><h3>{item.title}</h3></article>}
const objectives=[['Provide Quality','Providing high-quality services and products.',Target],['Create Awareness & Training','Creating awareness and training through workshops and seminars.',BookOpen],['Manage Business Ventures','Investing in and managing various business ventures.',TrendingUp],['Support Katsina Development','Contributing to the development of Katsina State as Katsinawa.',MapPinned]];

export function HomePage(){return <>
 <section className="hero"><div className="container hero-content"><span className="hero-kicker">HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED</span><h1>Delivering excellence.<br/><em>Building relationships.</em><br/>Growing communities.</h1><p>A diversified Nigerian company with interests in building, welding, manufacturing, installation, provisions, trading, and services.</p><div className="actions"><Link className="btn btn-primary" to="/services">Explore Our Services <ArrowRight/></Link><Link className="btn btn-outline-light" to="/quote">Request a Quote</Link></div><span className="rc">Registered with CAC · RC No. 1632978</span></div><div className="hero-side"><span>14</span><p>Core service<br/>categories.</p></div></section>
 <section><div className="container split"><div className="image-stack"><img src="https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85" alt="Industrial welding professional"/><div className="experience"><b>Katsina</b><span>Katsina State, Nigeria.</span></div></div><div><span className="eyebrow">WHO WE ARE</span><h2>Delivering excellent services and building strong relationships.</h2><p>HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED is a diversified Nigerian company with interests in building, welding, manufacturing, installation, provisions, trading, and services.</p><p>Based in Katsina State, we are committed to contributing to the growth of the local economy.</p><Link className="text-link" to="/about">Discover our company <ArrowRight/></Link></div></div></section>
 <section className="section-alt"><div className="container"><SectionHeader eyebrow="WHAT WE DO" title="Our services." text="Services across building, welding, manufacturing, installation, trading, and more."/><div className="service-grid">{services.slice(0,6).map(s=><ServiceCard key={s.id} service={s}/>)}</div><div className="center"><Link className="btn btn-secondary" to="/services">View all 14 services <ArrowRight/></Link></div></div></section>
 <section><div className="container"><SectionHeader eyebrow="INDUSTRIES WE SERVE" title="Diverse areas of interest."/><div className="industry-grid">{industries.slice(0,4).map(i=><IndustryCard key={i.title} item={i}/>)}</div></div></section>
 <section className="why"><div className="container"><SectionHeader light eyebrow="OUR COMMITMENT" title="Quality, safety, and community development."/><div className="feature-grid">{[[Award,'Quality','We are committed to quality in our services and products.'],[ShieldCheck,'Safety','We are committed to safety.'],[HeartHandshake,'Community Development','We are committed to community development.'],[Layers3,'Youth Empowerment','Through ALHIKMAH WELDERS FOUNDATION, we engage in youth empowerment, skills training, and charity work.']].map(([I,t,p])=><div key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
 <section><div className="container"><SectionHeader eyebrow="OUR OBJECTIVES" title="Growing businesses and communities."/><div className="objective-grid">{objectives.map(([t,p,I],n)=><div key={t}><span>0{n+1}</span><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
 <section className="stats"><div className="container">{[['14','Core Services'],['RC 1632978','CAC Registration'],['Katsina State','Based In'],['Nigeria','Country']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section><CTA/><section className="home-contact"><div className="container"><SectionHeader eyebrow="CONTACT HIGH TECH" title="Ready to discuss your requirements?" text="Reach our team by phone or email, or visit us in Katsina State, Nigeria."/><ContactCards/></div></section>
 </>}

export function AboutPage(){return <><PageHero eyebrow="ABOUT HIGH TECH" title="Delivering excellence. Building relationships. Growing communities." text="A diversified Nigerian company based in Katsina State."/><section><div className="container split"><div><span className="eyebrow">COMPANY OVERVIEW</span><h2>A diversified Nigerian company.</h2><p>HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED is a diversified Nigerian company with interests in building, welding, manufacturing, installation, provisions, trading, and services.</p><p>Registered with CAC RC: 1632978 and based in Katsina State, we are committed to delivering excellent services, building strong relationships, and contributing to the growth of the local economy.</p></div><img className="rounded-image" src="https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=85" alt="Engineering operations"/></div></section><section className="section-alt"><div className="container mission-grid"><div><ShieldCheck/><span className="eyebrow">OUR COMMITMENT</span><h2>Quality, safety, and community development.</h2><p>We are committed to quality, safety, and community development.</p></div><div><HeartHandshake/><span className="eyebrow">ALHIKMAH WELDERS FOUNDATION</span><h2>Empowering communities.</h2><p>Through our affiliate ALHIKMAH WELDERS FOUNDATION, we engage in youth empowerment, skills training, and charity work across the 34 LGAs of Katsina State.</p></div></div></section><section><div className="container"><SectionHeader eyebrow="OUR OBJECTIVES" title="What guides our work."/><div className="objective-grid">{objectives.map(([t,p,I],n)=><div key={t}><span>0{n+1}</span><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section><section className="section-alt"><div className="container founder-content"><span className="eyebrow">FOUNDER & CHAIRMAN</span><h2>Doro</h2><p><b>Founder & Chairman</b><br/>HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED</p><p><b>Founder - ALHIKMAH WELDERS FOUNDATION</b></p><p>Doro is a visionary entrepreneur, technical consultant, and community development advocate from Katsina State.</p><p>As the Founder and Chairman of HIGH TECH & TECHNOLOGY WELDERS CONSULT NIGERIA LIMITED RC: 1632978, he leads a diversified company providing welding, manufacturing, trading, energy, and installation services across Nigeria.</p><p>Driven by the passion to reduce unemployment and empower communities, Doro established ALHIKMAH WELDERS FOUNDATION to train youths in welding and fabrication, support education, and care for the less privileged. The Foundation is currently focused on skills training for the AKK Gas Pipeline Project and other industrial opportunities.</p><p>Doro believes in building businesses that create jobs and impact lives. He is committed to supporting the development agenda of Katsina State and working with government and private partners to grow the local economy.</p></div></section><CTA/></>}

export function ServicesPage(){const [filter,setFilter]=useState('All');const groups={Engineering:[1,2],Energy:[6,7],Commercial:[3,4,8,9,11,12],Agriculture:[5],Security:[10],'Property & Mobility':[13,14]};const shown=filter==='All'?services:services.filter(s=>groups[filter].includes(s.id));return <><PageHero eyebrow="OUR SERVICES" title="Services across multiple industries." text="Explore our official service categories."/><section><div className="container"><div className="filters" aria-label="Filter services">{['All',...Object.keys(groups)].map(group=><button type="button" className={filter===group?'active':''} aria-pressed={filter===group} onClick={()=>setFilter(group)} key={group}>{group}</button>)}</div><div className="service-grid">{shown.map(s=><ServiceCard key={s.id} service={s}/>)}</div></div></section><CTA/></>}
export function IndustriesPage(){return <><PageHero eyebrow="INDUSTRIES" title="Diverse areas of interest." text="Our services cover building, manufacturing, energy, agriculture, trading, and related sectors."/><section><div className="container industry-grid full">{industries.map(i=><IndustryCard key={i.title} item={i}/>)}</div></section><CTA/></>}
export function ProjectsPage(){return <><PageHero eyebrow="PROJECTS & PORTFOLIO" title="Project information coming soon." text="Company-approved project details will be shared here when available."/><section><div className="container"><div className="empty-state"><ShieldCheck/><h2>Verified project details are not yet available.</h2><p>We will publish company-approved project information when it is supplied.</p><Link className="btn btn-primary" to="/contact">Contact Us <ArrowRight/></Link></div></div></section><CTA/></>}

const options=services.map(s=><option value={s.title} key={s.id}>{s.title}</option>);
function Form({quote=false}){const [sent,setSent]=useState(false);const submit=e=>{e.preventDefault();if(e.currentTarget.checkValidity()){setSent(true);e.currentTarget.reset()}};return <form onSubmit={submit} className="form"><div className="form-grid"><label>Full Name<input required name="name" placeholder="Your full name"/></label>{quote&&<label>Company / Organization<input name="company" placeholder="Company name"/></label>}<label>Email Address<input required type="email" name="email" placeholder="you@example.com"/></label><label>Phone Number<input required type="tel" name="phone" placeholder="0800 000 0000"/></label><label>Service {quote?'Required':'Interested In'}<select required defaultValue=""><option value="" disabled>Select a service</option>{options}</select></label>{quote&&<><label>Project Location<input required name="location" placeholder="City, State"/></label><label>Estimated Budget<select name="budget" defaultValue=""><option value="">Select a range</option><option>Under ₦500,000</option><option>₦500,000 – ₦2,000,000</option><option>₦2,000,000 – ₦10,000,000</option><option>Above ₦10,000,000</option></select></label><label>Preferred Start Date<input type="date" name="date"/></label></>}{!quote&&<label className="wide">Subject<input required name="subject" placeholder="How can we help?"/></label>}<label className="wide">{quote?'Project Description':'Message'}<textarea required rows="6" name="message" placeholder="Tell us about your requirements..."/></label></div><button className="btn btn-primary" type="submit">{quote?'Submit Quote Request':'Send Message'} <ArrowRight/></button>{sent&&<p className="success"><CheckCircle2/>Thank you. Your {quote?'quote request':'message'} has been received.</p>}</form>}
export function ContactPage(){return <><PageHero eyebrow="CONTACT US" title="Let’s start a conversation." text="Tell us about your requirements and our team will be ready to help."/><section><div className="container"><ContactCards/><div className="contact-layout"><div><span className="eyebrow">SEND A MESSAGE</span><h2>How can we help?</h2><p>Complete the form and our team will respond using the details you provide.</p><div className="contact-note"><HeartHandshake/><div><b>Prefer to speak directly?</b><p>Call 0803 096 5094 or 0701 666 6399.</p></div></div></div><Form/></div></div></section></>}
export function QuotePage(){return <><PageHero eyebrow="REQUEST A QUOTE" title="Tell us about your next project." text="Share a few details and help us understand the service you need."/><section><div className="container narrow"><div className="quote-intro"><ShieldCheck/><div><h2>Project enquiry</h2><p>Your information will only be used to respond to this request.</p></div></div><Form quote/></div></section></>}
export function NotFound(){return <section className="not-found"><span>404</span><h1>Page not found</h1><p>The page you requested does not exist.</p><Link className="btn btn-primary" to="/">Return Home</Link></section>}
